# Workflow derived from https://github.com/r-lib/actions/tree/master/examples

on: [push, pull_request]

name: shiny-deploy

jobs:
  shiny-deploy:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      APP_DIR: "app"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SHINYAPP_APIKEY: ${{ secrets.SHINYAPP_APIKEY }}
      R_KEEP_PKG_SOURCE: yes

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install shinytest dependencies
        run: |
          shinytest::installDependencies()
        shell: Rscript {0}

      - name: Run shinytest tests
        run: |
          shinytest::testApp("${{ env.APP_DIR }}")
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        env:
          SHINYAPP_NAME: ${{ secrets.SHINYAPP_NAME }}
          SHINYAPP_TOKEN: ${{ secrets.SHINYAPP_TOKEN }}
          SHINYAPP_SECRET: ${{ secrets.SHINYAPP_SECRET }}
        run: Rscript deploy.R
